### PR TITLE
Fixed a compile error in AtomicRefCounted tests

### PR DESCRIPTION
**Pull request by snej**
In LiteCore PR https://github.com/couchbase/couchbase-lite-core/pull/2503 the Ubuntu build failed with a GCC error building Fleece tests, in 
```
couchbase-lite-core/vendor/fleece/Tests/SupportTests.cc:476:15: error: alias template 'AtomicRef' requires template arguments; argument deduction only allowed for class templates
  476 |     AtomicRef r = new AtomicRetainedTest();
```
This is a regression introduced by #272 / #303 but it wasn't caught in Fleece's CI, apparently because Fleece's CI builds with GCC on Ubuntu, while LiteCore builds with Clang; and probably a different Clang than Fleece uses on macOS since it didn't get this error either.

### CODE REVIEW

**Review by pasin — COMMENTED** [review]
There is also a failure on Android (32 bits) in PR validation done by Jenkins, [here](https://mobile.jenkins.couchbase.com/blue/organizations/jenkins/_cbl_github_pipeline%2Fcouchbase-lite-core/detail/PR-2503/3/pipeline).

```
[2026-06-17T19:36:53.163Z] /home/couchbase/jenkins/workspace/line_couchbase-lite-core_PR-2503/couchbase-lite-core/vendor/fleece/Fleece/Support/RefCounted.cc:139:36: error: constexpr variable 'kBusyMask' must be initialized by a constant expression

[2026-06-17T19:36:53.163Z]   139 |         static constexpr uintptr_t kBusyMask = uintptr_t(1) << 63;

[2026-06-17T19:36:53.163Z]       |                                    ^           ~~~~~~~~~~~~~~~~~~

[2026-06-17T19:36:53.163Z] /home/couchbase/jenkins/workspace/line_couchbase-lite-core_PR-2503/couchbase-lite-core/vendor/fleece/Fleece/Support/RefCounted.cc:139:61: note: shift count 63 >= width of type 'uintptr_t' (aka 'unsigned int') (32 bits)

[2026-06-17T19:36:53.163Z]   139 |         static constexpr uintptr_t kBusyMask = uintptr_t(1) << 63;
```

**Review by borrrden — APPROVED** [review]

**Review by pasin — APPROVED** [review]
